# 如果您的项目需要赞助支持，可以在这里配置
# 支持的平台包括：GitHub Sponsors, Open Collective, Ko-fi, 等

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-collective-name
# ko_fi: your-kofi-username
# custom: ["https://your-website.com", "https://another-site.com"]

# 示例：
# github: campcooking
# custom: ["https://donate.example.com"]

